{
 "title": "Renault ZOE",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Vehicle",
    "query": "show tag values with key = \"vehicle\""
   }
  ]
 },
 "panels": [
  {
   "title": "Last update",
   "type": "stat",
   "description": "Shows the latest updates from the InfluxDB database. If the Renault API is out, it will show an old time.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=~", "value": "/^$Vehicle$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery status",
   "type": "gauge",
   "description": "Here you can see the status of the battery. This expires as soon as you have driven with the car.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=~", "value": "/^$Vehicle$/" }
     ]
    }
   ]
  },
  {
   "title": "GoM Range",
   "type": "gauge",
   "description": "Here you can see the number of kilometers that can still be driven before the car is empty.",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "battery",
     "select": [
      [
       { "params": [ "range" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=~", "value": "/^$Vehicle$/" }
     ]
    }
   ]
  },
  {
   "title": "Available energy",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "battery",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=~", "value": "/^$Vehicle$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery temperature",
   "type": "gauge",
   "description": "This graph shows the temperature of the battery.",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "batterytemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=~", "value": "/^$Vehicle$/" }
     ]
    }
   ]
  },
  {
   "title": "Total milage",
   "type": "graph",
   "description": "Shows the total kilometers driven by the car.",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "km",
     "measurement": "car",
     "select": [
      [
       { "params": [ "milage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=~", "value": "/^$Vehicle$/" }
     ]
    }
   ]
  },
  {
   "title": "Is the car connected to the charging station?",
   "type": "singlestat",
   "description": "This shows whether the car is connected to a charging station.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "charging",
     "select": [
      [
       { "params": [ "pluggedin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=~", "value": "/^$Vehicle$/" }
     ]
    }
   ]
  },
  {
   "title": "Is the car charging at a charging station?",
   "type": "singlestat",
   "description": "Indicates the status of the charging.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "charging",
     "select": [
      [
       { "params": [ "charging" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=~", "value": "/^$Vehicle$/" }
     ]
    }
   ]
  },
  {
   "title": "GoM Range",
   "type": "graph",
   "description": "This graph shows the starting kilometers for battery and the amount driven battery. That way you can see what the consumption is.",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "yaxes": [
    { "format": "lengthkm" }
   ],
   "targets": [
    {
     "alias": "Kilometers",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "range" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=~", "value": "/^$Vehicle$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging time",
   "type": "stat",
   "description": "Charging time needed to charge the battery to 100% (based on the charging capacity of the last used charging point).",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "charging",
     "select": [
      [
       { "params": [ "remainingtime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=~", "value": "/^$Vehicle$/" }
     ]
    }
   ]
  },
  {
   "title": "Location",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "car",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "longitude" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "vehicle", "operator": "=~", "value": "/^$Vehicle$/" }
     ]
    }
   ]
  }
 ]
}